language: bash
arch:
  - arm64
  - amd64
os:
  - osx
  - windows
  - linux
env:
  global:
    - TERM=dumb
    - PUBLISH="false"
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
  matrix:
    - JDK="adopt@1.11"
    - JDK="adopt"
jobs:
  exclude:
    - arch: arm64
      os: osx
before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk
script:
  - ./gradlew runAll --stacktrace
before_cache:
  - GRAVIS/clean-gradle-cache
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  recipients:
    - danilo.pianini@unibo.it
    - mirko.viroli@unibo.it
  email:
    on_success: never
    on_failure: always
